apiVersion: v1

kind: Pod

metadata:
  name: mi-app2
  labels:
    app: web2

spec:
  containers:
    - name: front-end2
      image: nginx
      ports:
        - containerPort: 80

    - name: back-end2
      image: redis
