apiVersion: v1
kind: Pod
metadata:
  name: test-pd-hp
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd-hp
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # ruta directorio en el host
      path: /data
      # campo opcional
      type: Directory

